name: ipython-notebook
dependencies:
  - notebook
  - ipywidgets
  - requests
  # get dependencies for pgcontents
  - certifi
  - click
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip:
    - git+git://github.com/pl31/pgcontents.git
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
    - git+git://github.com/heitzmann/gdspy.git
    - git+git://github.com/ryanpepper/tcl_kernel.git
